### ISSUE TITLE
sortable bug

### ISSUE THREAD

**Issue by dsmalko** [aaronchi/jrails#1]
jrails.rb:367

options[:with] ||= "#{JQUERY_VAR}(this).sortable('serialize',{key:'#{element_id}[]'})"

should be:

options[:with] ||= "#{JQUERY_VAR}(this).sortable('serialize',{key:'#{element_id}'})"

**Comment by leandrocg** [comment]
This is about the sortable_element, rigth?
Actually, in my code, it is in line 363 and is without the []. In my case, it should be WITH the [] in the serialize/key in order to convert in a params[:items] array of ordered element ids. Maybe thats because i am using it on tbody tr's.

Other issue is that it should have a ";" in the end of the final generated js line.

**Comment by masnick** [comment]
I fixed this myself according to leandrocg's comment and it works fine.
